# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
